Ext.define('YMPI.model.m_gajibulanan', {
	extend: 'Ext.data.Model',
	alias		: 'widget.gajibulananModel',
	fields		: ['BULAN','NIK','NAMAKAR','SINGKATAN','NAMALEVEL','STATUSKAR','GRADE','TGLMASUK'
				   ,'NPWP','SISACUTI'
				   ,'RPUPAHPOKOK','RPTUNJTETAP','RPTUNJTDKTTP','RPNONUPAH','RPTOTGAJI','NOACCKAR','NAMABANK','TGLDIBAYAR','USERNAME'
				   ,'RPUMSK','RPTJABATAN','RPTANAK','RPTISTRI','RPTBHS','RPTTRANSPORT','RPTSHIFT'
				   ,'RPTPEKERJAAN','RPTQCP','RPTHADIR','RPTLEMBUR','RPIDISIPLIN','RPKOMPEN'
				   ,'RPTMAKAN','RPTSIMPATI','RPPUPAHPOKOK','RPPMAKAN','RPPTRANSPORT'
				   ,'RPPJAMSOSTEK','RPCICILAN1','RPCICILAN2','RPTAMBAHAN','RPPOTONGAN','RPPOTSP'
				   ,'BTAMBAHAN_KODEUPAH','BTAMBAHAN_NAMAUPAH','BTAMBAHAN_KETERANGAN','BTAMBAHAN_RPTAMBAHAN'
				   ,'JTAMBAHAN_KODEUPAH','JTAMBAHAN_NAMAUPAH','JTAMBAHAN_KETERANGAN','JTAMBAHAN_RPTAMBAHAN'
				   ,'LTAMBAHAN_KODEUPAH','LTAMBAHAN_NAMAUPAH','LTAMBAHAN_KETERANGAN','LTAMBAHAN_RPTAMBAHAN'
				   ,'BPOTONGAN_KODEPOTONGAN','BPOTONGAN_NAMAPOTONGAN','BPOTONGAN_KETERANGAN','BPOTONGAN_RPPOTONGAN'
				   ,'JPOTONGAN_KODEPOTONGAN','JPOTONGAN_NAMAPOTONGAN','JPOTONGAN_KETERANGAN','JPOTONGAN_RPPOTONGAN'
				   ,'LPOTONGAN_KODEPOTONGAN','LPOTONGAN_NAMAPOTONGAN','LPOTONGAN_KETERANGAN','LPOTONGAN_RPPOTONGAN']
});