Ext.define('YMPI.model.m_td_training', {
	extend: 'Ext.data.Model',
	alias		: 'widget.td_trainingModel',
	fields		: ['TDTRAINING_ID','TDTRAINING_KODE','TDTRAINING_NAMA','TDTRAINING_KETERANGAN','TDTRAINING_TDKELOMPOK_ID'
		,'TDTRAINING_TDKELOMPOK_NAMA','TDTRAINING_TUJUAN','TDTRAINING_JENIS','TDTRAINING_SIFAT','TDTRAINING_CREATED_BY'
		,'TDTRAINING_CREATED_DATE','TDTRAINING_UPDATED_BY','TDTRAINING_UPDATED_DATE','TDTRAINING_REVISED'],
	idProperty	: 'TDTRAINING_ID'	
});