Ext.define('YMPI.model.m_td_pelatihan', {
	extend: 'Ext.data.Model',
	alias		: 'widget.td_pelatihanModel',
	fields		: ['TDPELATIHAN_ID','TDPELATIHAN_NO','TDPELATIHAN_TANGGAL','TDPELATIHAN_DIBUAT','TDPELATIHAN_DIBUAT_NAMA'
		,'TDPELATIHAN_DIPERIKSA','TDPELATIHAN_DIPERIKSA_NAMA','TDPELATIHAN_DIKETAHUI','TDPELATIHAN_DIKETAHUI_NAMA'
		,'TDPELATIHAN_DISETUJUI01','TDPELATIHAN_DISETUJUI01_NAMA','TDPELATIHAN_DISETUJUI02','TDPELATIHAN_DISETUJUI02_NAMA'
		,'TDPELATIHAN_DISETUJUI03','TDPELATIHAN_DISETUJUI03_NAMA','TDPELATIHAN_TDTRAINING_ID','TDPELATIHAN_TDTRAINING_NAMA'
		,'TDPELATIHAN_TDKELOMPOK_ID','TDPELATIHAN_TDKELOMPOK_NAMA','TDPELATIHAN_TDTRAINING_TUJUAN','TDPELATIHAN_TDTRAINING_JENIS'
		,'TDPELATIHAN_TDTRAINING_SIFAT','TDPELATIHAN_PESERTA','TDPELATIHAN_PESERTA_JUMLAH','TDPELATIHAN_DURASI'
		,'TDPELATIHAN_BIAYA_PLAN','TDPELATIHAN_BIAYA_AKTUAL','TDPELATIHAN_BIAYA_BALANCE','TDPELATIHAN_TDTRAINER_ID'
		,'TDPELATIHAN_TDTRAINER_NAMA','TDPELATIHAN_EVREAKSI','TDPELATIHAN_EVEFFECTIVITAS','TDPELATIHAN_CREATED_BY'
		,'TDPELATIHAN_CREATED_DATE','TDPELATIHAN_UPDATED_BY','TDPELATIHAN_UPDATED_DATE','TDPELATIHAN_REVISED'
		,'TDRENCANA_TANGGAL','TDREALISASI_TANGGAL'],
	idProperty	: 'TDPELATIHAN_ID'	
});