Ext.define('YMPI.model.m_detilgaji', {
	extend: 'Ext.data.Model',
	alias		: 'widget.detilgajiModel',
	fields		: ['BULAN','NIK','NOREVISI','RPUPAHPOKOK','RPTANAK','RPTBHS','RPTHR','RPTISTRI','RPTJABATAN','RPTPEKERJAAN','RPTSHIFT','RPTTRANSPORT','RPBONUS','RPIDISIPLIN','RPTLEMBUR','RPTKACAMATA','RPTSIMPATI','RPTMAKAN','RPPSKORSING','RPPSAKITCUTI','RPPJAMSOSTEK','RPPOTONGAN','RPTAMBAHAN']	
});