Ext.define('YMPI.model.m_detilgaji', {
	extend: 'Ext.data.Model',
	alias		: 'widget.detilgajiModel',
	fields		: ['BULAN','NIK','NOREVISI'
				   ,'RPUPAHPOKOK','RPTJABATAN','RPTANAK','RPTISTRI','RPTBHS','RPTTRANSPORT','RPTSHIFT'
				   ,'RPTPEKERJAAN','RPTQCP','RPTLEMBUR','RPIDISIPLIN','RPTHADIR','RPKOMPEN','RPTMAKAN','RPTSIMPATI'
				   ,'RPTHR','RPBONUS','RPTKACAMATA','RPTAMBAHAN1','RPTAMBAHAN2','RPTAMBAHAN3','RPTAMBAHAN4'
				   ,'RPTAMBAHAN5','RPTAMBAHANLAIN','RPPUPAHPOKOK','RPPMAKAN','RPPTRANSPORT','RPPJAMSOSTEK'
				   ,'RPCICILAN1','RPCICILAN2','RPPOTONGAN1','RPPOTONGAN2','RPPOTONGAN3','RPPOTONGAN4'
				   ,'RPPOTONGAN5','RPPOTONGANLAIN','RPPOTSP','RPUMSK']	
});