Ext.define('YMPI.model.m_gajibulanan', {
	extend: 'Ext.data.Model',
	alias		: 'widget.gajibulananModel',
	fields		: ['BULAN','NIK','NAMAKAR','SINGKATAN','NAMALEVEL','STATUSKAR','GRADE','TGLMASUK'
				   ,'NPWP'
				   ,'RPUPAHPOKOK','RPTUNJTETAP','RPTUNJTDKTTP','RPNONUPAH','RPPOTONGAN','RPTAMBAHAN','RPTOTGAJI','NOACCKAR','NAMABANK','TGLDIBAYAR','USERNAME'
				   ,'RPUMSK','RPTJABATAN','RPTANAK','RPTISTRI','RPTBHS','RPTTRANSPORT','RPTSHIFT'
				   ,'RPTPEKERJAAN','RPTQCP','RPTHADIR','RPTLEMBUR','RPIDISIPLIN','RPKOMPEN'
				   ,'RPTMAKAN','RPTSIMPATI','RPPUPAHPOKOK','RPPMAKAN','RPPTRANSPORT'
				   ,'RPPJAMSOSTEK','RPCICILAN1','RPCICILAN2']
});