Ext.define('YMPI.model.m_karyawan', {
	extend: 'Ext.data.Model',
	alias		: 'widget.karyawanModel',
	fields		: ['NIK','KODEUNIT','KODEJAB','IDJAB','GRADE','NAMAKAR','TGLMASUK','JENISKEL','ALAMAT'
				   ,'DESA','RT','RW','KECAMATAN','KOTA','TELEPON','TMPLAHIR','TGLLAHIR','ANAKKE'
				   ,'JMLSAUDARA','PENDIDIKAN','JURUSAN','NAMASEKOLAH','AGAMA','NAMAAYAH','STATUSAYAH'
				   ,'ALAMATAYAH','PENDDKAYAH','PEKERJAYAH','NAMAIBU','STATUSIBU','ALAMATIBU','PENDDKIBU'
				   ,'PEKERJIBU','KAWIN','TGLKAWIN','NAMAPASANGAN','ALAMATPAS','TMPLAHIRPAS','TGLLAHIRPAS'
				   ,'AGAMAPAS','PEKERJPAS','KATPEKERJAAN','BHSJEPANG'
				   ,{name: 'JAMSOSTEK', type: 'bool'}
				   ,'TGLJAMSOSTEK','STATUS'
				   ,'TGLSTATUS','TGLMUTASI','NOURUTKTRK','TGLKONTRAK','LAMAKONTRAK','NOACCKAR','NAMABANK'
				   ,'FOTO','USERNAME','STATTUNKEL','ZONA'
				   ,{name: 'STATTUNTRAN', type: 'bool'}
				   ,'NAMASINGKAT','NPWP','KODESP'
				   ,'WARNATAGR','WARNATAGG','WARNATAGB'
				   ,'NAMAUNIT','NAMAKEL','KETERANGAN'],
	idProperty	: 'NIK'	
});