CREATE TABLE `presensibln` (
`NIK`  varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`BULAN`  varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`HARIKERJA`  int(11) NULL DEFAULT NULL ,
`EXTRADAY`  int(11) NULL DEFAULT NULL ,
`XPOTONG`  int(1) NULL DEFAULT NULL ,
`SATLEMBUR`  decimal(6,2) NULL DEFAULT NULL ,
PRIMARY KEY (`NIK`, `BULAN`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
ROW_FORMAT=Compact
;



ALTER TABLE `detilgaji` ADD COLUMN `HARIKERJA`  int(11) NULL DEFAULT 0 AFTER `RPUMSK`;
ALTER TABLE `detilgaji` ADD COLUMN `EXTRADAY`  int(11) NULL DEFAULT 0 AFTER `HARIKERJA`;
ALTER TABLE `detilgaji` ADD COLUMN `XPOTONG`  int(1) NULL DEFAULT 0 AFTER `EXTRADAY`;
ALTER TABLE `detilgaji` ADD COLUMN `SATLEMBUR`  decimal(6,2) NULL DEFAULT 0.00 AFTER `XPOTONG`;