SELECT @myRight := MENU_RGT FROM s_menus
WHERE MENU_ID = 539;

UPDATE s_menus SET MENU_RGT = MENU_RGT + 2 WHERE MENU_RGT > @myRight;
UPDATE s_menus SET MENU_LFT = MENU_LFT + 2 WHERE MENU_LFT > @myRight;

INSERT INTO s_menus(MENU_ID,
	MENU_KODE,
	MENU_PARENT,
	MENU_POSITION,
	MENU_TITLE,
	MENU_FILENAME,
	MENU_CAT,
	MENU_CONFIRM,
	MENU_LEFTPANEL,
	MENU_AKTIF, 
	MENU_LFT, 
	MENU_RGT) VALUES(540,'TKINERJA',5,40,'Penilaian Kinerja','TKINERJA','window','N','Y','Y', @myRight + 1, @myRight + 2);

INSERT INTO s_permissions(PERM_GROUP, PERM_MENU)
SELECT GROUP_ID, 540
FROM s_usergroups;