-- ----------------------------
-- Table structure for rekapjemputan
-- ----------------------------
DROP TABLE IF EXISTS `rekapjemputan`;
CREATE TABLE `rekapjemputan` (
  `NIK` varchar(10) NOT NULL,
  `BULAN` varchar(6) NOT NULL,
  `JMLJEMPUT` tinyint(2) unsigned DEFAULT '0',
  `KETERANGAN` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`NIK`,`BULAN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/*ADD MENU Rekap Jemputan Karyawan*/
LOCK TABLE s_menus WRITE;
SELECT @myRight := MENU_RGT FROM s_menus WHERE MENU_KODE = 'TRANSAKSI';

UPDATE s_menus SET MENU_RGT = MENU_RGT + 2 WHERE MENU_RGT >= @myRight;
UPDATE s_menus SET MENU_LFT = MENU_LFT + 2 WHERE MENU_LFT > @myRight;

INSERT INTO s_menus(MENU_ID, MENU_KODE, MENU_PARENT, MENU_POSITION, MENU_TITLE, MENU_FILENAME, MENU_LFT, MENU_RGT) 
VALUES(539, 'REKAPJEMPUTAN', 5, 39, 'Rekap Jemputan Karyawan', 'REKAPJEMPUTAN', @myRight, @myRight + 1);
UNLOCK TABLES;



ALTER TABLE `detilgaji` ADD COLUMN `RPPTRANSPORT_REKAP`  decimal(12,2) NULL DEFAULT NULL AFTER `JMLABSEN`;




ALTER TABLE `posisilowongan` DROP PRIMARY KEY;
ALTER TABLE `posisilowongan` ADD COLUMN `IDJAB`  varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `JMLPOSISI`;
ALTER TABLE `posisilowongan` ADD PRIMARY KEY (`GELLOW`, `KODEJAB`, `IDJAB`);




UPDATE s_menus
SET MENU_KODE = 'POSISILOWONGAN', MENU_FILENAME = 'POSISILOWONGAN'
WHERE MENU_ID = 524 AND MENU_KODE = 'POSLOWONGAN';
