ALTER TABLE `s_users` MODIFY COLUMN `USER_GROUP`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `USER_LOG`;


UPDATE s_menus SET MENU_POSITION = MENU_POSITION + 1, MENU_ID = MENU_ID + 1 WHERE MENU_ID = 105;


LOCK TABLE s_menus WRITE;
SELECT @myLeft := MENU_LFT, @myRight := MENU_RGT FROM s_menus WHERE MENU_ID = 106;

UPDATE s_menus SET MENU_RGT = MENU_RGT + 2 WHERE MENU_RGT >= @myRight;
UPDATE s_menus SET MENU_LFT = MENU_LFT + 2 WHERE MENU_LFT >= @myLeft;

INSERT INTO s_menus(MENU_ID, MENU_KODE, MENU_PARENT, MENU_POSITION, MENU_TITLE, MENU_FILENAME, MENU_LFT, MENU_RGT) 
VALUES(105, 'LOGOFF', 5, 1, 'LogOff', 'LOGOFF', @myLeft, @myRight);
UNLOCK TABLES;



INSERT INTO s_permissions(PERM_GROUP, PERM_MENU, PERM_PRIV)
SELECT GROUP_ID, 106, 'RCUD'
FROM s_usergroups;