ALTER TABLE `karyawan` DROP FOREIGN KEY `fk_karyawan_leveljabatan1`;
ALTER TABLE `karyawan` DROP FOREIGN KEY `fk_karyawan_jabatan1`;
ALTER TABLE `karyawan` MODIFY COLUMN `IDJAB`  varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `NIK`;
ALTER TABLE `karyawan` MODIFY COLUMN `KODEJAB`  varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `IDJAB`;
ALTER TABLE `karyawan` MODIFY COLUMN `GRADE`  char(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `KODEJAB`;
ALTER TABLE `karyawan` MODIFY COLUMN `KODEUNIT`  varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `GRADE`;