ALTER TABLE `detilgaji` ADD COLUMN `JMLJAMKURANG`  decimal(5,2) NULL DEFAULT NULL AFTER `SATLEMBUR`;


ALTER TABLE `hitungpresensi` ADD COLUMN `UPENGALI`  char(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `XPOTONG`;



ALTER TABLE `presensibln` ADD COLUMN `JMLJAMKURANG`  decimal(5,2) NULL DEFAULT NULL AFTER `SATLEMBUR`;