ALTER TABLE `detilgaji` MODIFY COLUMN `RPPOTSP`  decimal(12,2) NULL DEFAULT NULL AFTER `RPPOTONGANLAIN`;

ALTER TABLE `detilgaji` MODIFY COLUMN `RPUMSK`  decimal(12,2) NULL DEFAULT NULL AFTER `RPPOTSP`;